### ISSUE TITLE
BUG: Applying template to Product List block resets Filtering

### ISSUE THREAD

**Issue by teknoziz** [concrete5-community-store/community_store#200] opened 2017-03-09 18:56 UTC
Applying a custom template to an existing Product List block resets the product filtering to no filtering.

**Comment by Mesuva** [comment] 2017-03-09 23:46
I couldn't replicate this, apply a block template from the application directory didn't appear to have any impact on what filtering was enabled

**Comment by teknoziz** [comment] 2017-03-10 00:48
From the application directory? I'm not sure what you mean here.

**Comment by Mesuva** [comment] 2017-03-10 00:52
I created a template in /application/blocks/community_product_list/templates/custom_template.php and applied that as a test

**Comment by teknoziz** [comment] 2017-03-10 01:06
Oh gotcha. It did it repeatedly for 24 pages. Could something in the template be throwing it off?

**Comment by Mesuva** [comment] 2017-03-11 11:48
Is this related to the other issue you experienced with pagination?

**Comment by teknoziz** [comment] 2017-03-11 12:13
Other than it has to do with the Product List block, no. But I will see if your fix somehow addresses this issue as well. Please stand by... ;-)

**Comment by teknoziz** [comment] 2017-03-11 12:15
Nope. Went back to Template -> None Selected and the same thing happened.

**Comment by teknoziz** [comment] 2017-03-11 12:17
Odd though, I just went back and re-selected the template and this time it stuck. I am going to try it again.

**Comment by Mesuva** [comment] 2017-03-11 12:18
I'm wondering if you've got some caching going on. I'm not seeing anything unusual  (i'm just testing on 5.7 though, haven't checked in 8.1 yet)

**Comment by teknoziz** [comment] 2017-03-11 12:19
Aha! This time I saved the changes between template swaps and the problem occurred.

**Comment by teknoziz** [comment] 2017-03-11 12:20
All caching is off BTW.

**Comment by teknoziz** [comment] 2017-03-11 12:26
Just curious, what's the time difference between us? You're in Australia?

**Comment by Mesuva** [comment] 2017-03-11 12:29
Yep, South Australia. It's just hitting 11PM here. 

I'm not finding I can replicate this, I can change back and forth between a custom template and the default and I'm not finding it ever change what products (and pagination) it's displaying.

Are you running your c5 install out of a folder by any chance?

**Comment by teknoziz** [comment] 2017-03-11 12:31
I am using MAMP and I am running the install out of a subdirectory, is that what you mean? Heh, it's 7:30 am here.

**Comment by Mesuva** [comment] 2017-03-11 12:35
Yes, I've got a feeling that might be the cause of the issue here, with it being more of a core issue. 8.1 has had some issues with editing when it's running out of a directory, especially with cookies.

I submitted a fix for something and it was merged yesterday:
https://github.com/concrete5/concrete5/commit/8b80c072e210ecbb07d56915585f2193eff35d8e

You might want to try patching for that fix and seeing if it still persists. Otherwise you could try moving your site up a level.

I use MAMP, but I always set up subdomains, so I often miss issues that relate to running c5 in a folder

**Comment by teknoziz** [comment] 2017-03-11 12:37
Don't laugh, I have MAMP Pro and haven't quite figured out how to do that... would probably make my life easier in some ways. Would ya like to help a buddy out? LOL

**Comment by Mesuva** [comment] 2017-03-11 12:39
I only run the normal MAMP, so I honestly don't know how it's managed in the pro version.

I wrote this _years_ ago, but I think it's still the same steps:
http://www.mesuva.com.au/blog/technical-notes/running-multiple-development-sites-on-one-machine/

**Comment by teknoziz** [comment] 2017-03-11 12:44
Great I will check it out. Thanks, and I'll send you a follow up on the cookie issue and for that project that I had asked if you were available for. Thanks for all your help thus far.

**Closed** 2017-05-28 06:46 UTC
