### ISSUE TITLE
C5 8.3.1 - CS Latest Git - Using the product list block to show related products gives error

### ISSUE THREAD

**Issue by MichaelMaar** [concrete5-community-store/community_store#330] opened 2018-01-16 16:14 UTC
I have added a product list block on the product detail page filtering after related products. When no related products are added to the product then no error. But if just one product has been added to the product related product page when entering the single product page it gives an error:

Doctrine\DBAL\Exception\NonUniqueFieldNameException thrown with message "An exception occurred while executing 'SELECT p.pID FROM CommunityStoreProducts p LEFT JOIN CommunityStoreProductSearchIndexAttributes csi ON p.pID = csi.pID WHERE (p.pID in (4)) AND (pQty > 0 OR pQtyUnlim = 1) AND (pActive = 1) GROUP BY p.pID ORDER BY FIELD (pID, 4) ASC':

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'pID' in order clause is ambiguous"

Stacktrace:
#53 Doctrine\DBAL\Exception\NonUniqueFieldNameException in /var/www/clients/client1/web32/web/concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:76
#52 Doctrine\DBAL\Driver\AbstractMySQLDriver:convertException in /var/www/clients/client1/web32/web/concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
#51 Doctrine\DBAL\DBALException:driverExceptionDuringQuery in /var/www/clients/client1/web32/web/concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:855
#50 Doctrine\DBAL\Driver\PDOException in /var/www/clients/client1/web32/web/concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106
#49 PDOException in /var/www/clients/client1/web32/web/concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
#48 PDO:query in /var/www/clients/client1/web32/web/concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
#47 Doctrine\DBAL\Driver\PDOConnection:query in /var/www/clients/client1/web32/web/concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:852
#46 Doctrine\DBAL\Connection:executeQuery in /var/www/clients/client1/web32/web/concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
#45 Doctrine\DBAL\Query\QueryBuilder:execute in /var/www/clients/client1/web32/web/packages/community_store/src/CommunityStore/Product/ProductList.php:233
#44 Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductList:Concrete\Package\CommunityStore\Src\CommunityStore\Product\{closure} in /var/www/clients/client1/web32/web/concrete/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Adapter/DoctrineDbalAdapter.php:60
#43 call_user_func in /var/www/clients/client1/web32/web/concrete/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Adapter/DoctrineDbalAdapter.php:60
#42 Pagerfanta\Adapter\DoctrineDbalAdapter:prepareCountQueryBuilder in /var/www/clients/client1/web32/web/concrete/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Adapter/DoctrineDbalAdapter.php:51
#41 Pagerfanta\Adapter\DoctrineDbalAdapter:getNbResults in /var/www/clients/client1/web32/web/concrete/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Pagerfanta.php:359
#40 Pagerfanta\Pagerfanta:getNbResults in /var/www/clients/client1/web32/web/concrete/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Pagerfanta.php:388
#39 Pagerfanta\Pagerfanta:calculateNbPages in /var/www/clients/client1/web32/web/concrete/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Pagerfanta.php:377
#38 Pagerfanta\Pagerfanta:getNbPages in /var/www/clients/client1/web32/web/concrete/vendor/pagerfanta/pagerfanta/src/Pagerfanta/View/DefaultView.php:62
#37 Pagerfanta\View\DefaultView:initializePagerfanta in /var/www/clients/client1/web32/web/concrete/vendor/pagerfanta/pagerfanta/src/Pagerfanta/View/DefaultView.php:49
#36 Pagerfanta\View\DefaultView:render in /var/www/clients/client1/web32/web/concrete/src/Search/Pagination/View/ViewRenderer.php:29
#35 Concrete\Core\Search\Pagination\View\ViewRenderer:render in /var/www/clients/client1/web32/web/concrete/src/Search/Pagination/Pagination.php:81
#34 Concrete\Core\Search\Pagination\Pagination:renderView in /var/www/clients/client1/web32/web/concrete/src/Search/Pagination/Pagination.php:72
#33 Concrete\Core\Search\Pagination\Pagination:renderDefaultView in /var/www/clients/client1/web32/web/packages/community_store/blocks/community_product_list/controller.php:154
#32 Concrete\Package\CommunityStore\Block\CommunityProductList\Controller:view in /var/www/clients/client1/web32/web/concrete/src/Controller/AbstractController.php:294
#31 call_user_func_array in /var/www/clients/client1/web32/web/concrete/src/Controller/AbstractController.php:294
#30 Concrete\Core\Controller\AbstractController:runAction in /var/www/clients/client1/web32/web/concrete/src/Block/View/BlockView.php:448
#29 Concrete\Core\Block\View\BlockView:runControllerTask in /var/www/clients/client1/web32/web/concrete/src/Block/View/BlockView.php:150
#28 Concrete\Core\Block\View\BlockView:setupRender in /var/www/clients/client1/web32/web/concrete/src/View/AbstractView.php:148
#27 Concrete\Core\View\AbstractView:render in /var/www/clients/client1/web32/web/concrete/src/Area/Area.php:873
#26 Concrete\Core\Area\Area:display in /var/www/clients/client1/web32/web/packages/theme_pixel/themes/pixel/default.php:14
#25 include in /var/www/clients/client1/web32/web/concrete/src/View/View.php:100
#24 Concrete\Core\View\View:inc in /var/www/clients/client1/web32/web/packages/theme_pixel/themes/pixel/full.php:3
#23 include in /var/www/clients/client1/web32/web/concrete/src/View/View.php:254
#22 Concrete\Core\View\View:renderTemplate in /var/www/clients/client1/web32/web/concrete/src/View/View.php:216
#21 Concrete\Core\View\View:renderViewContents in /var/www/clients/client1/web32/web/concrete/src/View/AbstractView.php:151
#20 Concrete\Core\View\AbstractView:render in /var/www/clients/client1/web32/web/concrete/src/Http/ResponseFactory.php:147
#19 Concrete\Core\Http\ResponseFactory:view in /var/www/clients/client1/web32/web/concrete/src/Http/ResponseFactory.php:209
#18 Concrete\Core\Http\ResponseFactory:controller in /var/www/clients/client1/web32/web/concrete/src/Http/ResponseFactory.php:369
#17 Concrete\Core\Http\ResponseFactory:collection in /var/www/clients/client1/web32/web/concrete/src/Routing/DispatcherRouteCallback.php:34
#16 Concrete\Core\Routing\DispatcherRouteCallback:execute in /var/www/clients/client1/web32/web/concrete/src/Http/DefaultDispatcher.php:122
#15 Concrete\Core\Http\DefaultDispatcher:handleDispatch in /var/www/clients/client1/web32/web/concrete/src/Http/DefaultDispatcher.php:54
#14 Concrete\Core\Http\DefaultDispatcher:dispatch in /var/www/clients/client1/web32/web/concrete/src/Http/Middleware/DispatcherDelegate.php:39
#13 Concrete\Core\Http\Middleware\DispatcherDelegate:next in /var/www/clients/client1/web32/web/concrete/src/Http/Middleware/ThumbnailMiddleware.php:71
#12 Concrete\Core\Http\Middleware\ThumbnailMiddleware:process in /var/www/clients/client1/web32/web/concrete/src/Http/Middleware/MiddlewareDelegate.php:38
#11 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /var/www/clients/client1/web32/web/concrete/src/Http/Middleware/FrameOptionsMiddleware.php:39
#10 Concrete\Core\Http\Middleware\FrameOptionsMiddleware:process in /var/www/clients/client1/web32/web/concrete/src/Http/Middleware/MiddlewareDelegate.php:38
#9 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /var/www/clients/client1/web32/web/concrete/src/Http/Middleware/CookieMiddleware.php:37
#8 Concrete\Core\Http\Middleware\CookieMiddleware:process in /var/www/clients/client1/web32/web/concrete/src/Http/Middleware/MiddlewareDelegate.php:38
#7 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /var/www/clients/client1/web32/web/concrete/src/Http/Middleware/ApplicationMiddleware.php:29
#6 Concrete\Core\Http\Middleware\ApplicationMiddleware:process in /var/www/clients/client1/web32/web/concrete/src/Http/Middleware/MiddlewareDelegate.php:38
#5 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /var/www/clients/client1/web32/web/concrete/src/Http/Middleware/MiddlewareStack.php:86
#4 Concrete\Core\Http\Middleware\MiddlewareStack:process in /var/www/clients/client1/web32/web/concrete/src/Http/DefaultServer.php:85
#3 Concrete\Core\Http\DefaultServer:handleRequest in /var/www/clients/client1/web32/web/concrete/src/Foundation/Runtime/Run/DefaultRunner.php:115
#2 Concrete\Core\Foundation\Runtime\Run\DefaultRunner:run in /var/www/clients/client1/web32/web/concrete/src/Foundation/Runtime/DefaultRuntime.php:102
#1 Concrete\Core\Foundation\Runtime\DefaultRuntime:run in /var/www/clients/client1/web32/web/concrete/dispatcher.php:36
#0 require in /var/www/clients/client1/web32/web/index.php:3

I have a hard time to figure out where the problem is.

**Comment by MichaelMaar** [comment] 2018-01-16 16:50
Sorry, in witch file do you see that?

**Comment by mnakalay** [comment] 2018-01-16 18:16
in file src/CommunityStore/Product/ProductList.php line 191 pID should be p.pID

Now here's an explanation.

you error says Column 'pID' in order clause is ambiguous
So you look at the sql that seems to have a problem, still in the error message, and you look for the order clause which is:

`ORDER BY FIELD (pID, 4) ASC`

Then you look in the stacktrace and you see, starting from the top, that the first Community Store file is src/CommunityStore/Product/ProductList.php and it says line 233 but that doesn't necessarily mean anything.

Because the error happens because of a malformed query, it is safe to assume the problem happens in the finalizeQuery() where the query is built.

Now your query looks for pID in 2 different tables. See the beginning of the query:

`SELECT p.pID FROM CommunityStoreProducts p LEFT JOIN CommunityStoreProductSearchIndexAttributes csi ON p.pID = csi.pID`

We have the table CommunityStoreProducts that will be represented by the letter p in the query and we have CommunityStoreProductSearchIndexAttributes represented by csi. And both those tables have a column pID. o when referring to pID it is important to say if it is p.pID or csi.pID

And in the order cause at the and it only says pID so the system is confused, doesn't know which one it is.

If you look in that file at line 191 you will see

```
case "related":
                if (!empty($relatedids)) {
                    $query->addOrderBy('FIELD (pID, '. implode(',', $relatedids) .')');
                }
                break;
```

And you see your lonely pID used for related products. That should really be p.pID

I just loooooove long explanations :)

**Comment by mnakalay** [comment] 2018-01-16 18:22
I just corrected it in the master branch so you can correct it yourself or download it again

**Comment by MichaelMaar** [comment] 2018-01-16 18:57
That's an explanation!!! That's how to do it!!!
My cursor actually was standing on line 191, but I was just so confused.
Thanks a lot for the help!

**Comment by mnakalay** [comment] 2018-01-16 19:16
My pleasure.
Can you confirm it fixed the problem so I can close this issue? Thank you

**Comment by MichaelMaar** [comment] 2018-01-16 19:38
Yes, it seem to work as expected now. Now I just have to make some styling!
Again thanks...

**Closed** 2018-01-16 19:59 UTC
